<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>Sbn.Cms.Web.UI</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DocumentationFile>bin/Release/Sbn.Web.UI.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Sbn.PublishedCache.NuCache/Sbn.PublishedCache.NuCache.csproj" />
    <ProjectReference Include="../Sbn.Web.BackOffice/Sbn.Web.BackOffice.csproj" />
    <ProjectReference Include="../Sbn.Web.Common/Sbn.Web.Common.csproj" />
    <ProjectReference Include="../Sbn.Web.Website/Sbn.Web.Website.csproj" />
    <ProjectReference Include="../Sbn.Persistence.SqlCe/Sbn.Persistence.SqlCe.csproj" Condition="'$(OS)' == 'Windows_NT'" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Plugins" />
    <Folder Include="Views" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="sbn/logs/**" />
    <Compile Remove="sbn/mediacache/**" />
    <Compile Remove="wwwroot/sbn/**" />
    <Compile Remove="App_Data/**" />
    <Compile Remove="wwwroot\media\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="App_Data/**" />
    <EmbeddedResource Remove="sbn/logs/**" />
    <EmbeddedResource Remove="sbn/mediacache/**" />
    <EmbeddedResource Remove="wwwroot\media\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="App_Data/**" />
    <Content Remove="sbn/logs/**" />
    <Content Remove="sbn/mediacache/**" />
    <Content Remove="wwwroot\media\**" />
    <Content Remove="wwwroot/Web.config" />
  </ItemGroup>


  <ItemGroup>
    <None Include="config/**/*.*">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
    <None Include="sbn/**/*.*">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
    <None Remove="App_Data/**" />
    <None Remove="sbn/logs/**" />
    <None Remove="sbn/mediacache/**" />
    <None Remove="wwwroot\media\**" />
    <None Include="sbn/SbnWebsite/NoNodes.cshtml" />
  </ItemGroup>

  <!-- We don't want to include the generated files, they will throw a lot of errors -->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.10" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>

  <PropertyGroup>
    <BellePath>$(ProjectDir)wwwroot/sbn</BellePath>
    <JsonSchemaPath>$(ProjectDir)sbn/config/appsettings-schema.json</JsonSchemaPath>

  </PropertyGroup>
  <Target Name="CheckPreconditions" BeforeTargets="Build">
    <Message Text="-CheckPreconditions-" Importance="high" />
    <Message Text="JsonSchemaPath:  $(JsonSchemaPath)" Importance="high" />
    <Message Text="BellePath:       $(BellePath)" Importance="high" />

   <!-- Build Belle, if building is Visual Studio and the build folder does not exist yet -->
    <Message Text="Skip Belle because SbnBuild is '$(SbnBuild)' (this is not Visual Studio)." Importance="High" Condition="'$(SbnBuild)' != ''" />
    <Message Text="Skip Belle because $(BellePath) exists." Importance="High" Condition="Exists('$(BellePath)')" />
    <Message Text="Build Belle because SbnBuild is empty (this is Visual Studio), and $(BellePath) does not exist." Importance="High" Condition="!Exists('$(BellePath)') and '$(SbnBuild)' == ''" />
    <CallTarget Targets="BelleBuild" Condition="!Exists('$(BellePath)') and '$(SbnBuild)' == ''" />

    <Message Text="Skip JsonSchema generation because $(JsonSchemaPath) exists." Importance="High" Condition="Exists('$(JsonSchemaPath)')" />
    <Message Text="Generate the appsettings json schema." Importance="High" Condition="!Exists('$(JsonSchemaPath)') and '$(SbnBuild)' == ''" />

    <CallTarget Targets="JsonSchemaBuild" Condition="!Exists('$(JsonSchemaPath)') and '$(SbnBuild)' == ''" />
    
   
    <CallTarget Targets="AppsettingsBuild" Condition="!Exists('appsettings.json')" />
    <CallTarget Targets="AppsettingsDevBuild" Condition="!Exists('appsettings.Development.json')" />

  </Target>
  <Target Name="BelleBuild">
<!--    <Exec WorkingDirectory="$(ProjectDir)/../../src/Sbn.Web.UI.Client/" Command="powershell -ExecutionPolicy RemoteSigned -Command '&amp;{ npm install ; npm run build }'" />-->
  </Target>
  <Target Name="JsonSchemaBuild">
<!--    <Exec WorkingDirectory="$(ProjectDir)/../../" Command="powershell -ExecutionPolicy RemoteSigned -Command '&amp;dotnet run &#45;&#45;project $pwd/src/JsonSchema/JsonSchema.csproj -c Release &#45;&#45; &#45;&#45;outputFile $pwd/src/Sbn.Web.UI/$(JsonSchemaPath)'" />-->
  </Target>
  <Target Name="AppsettingsBuild">
     <Message Text="Generating appsettings.json because it doesnt exist" Importance="High" />
     <Copy SourceFiles="$(Projectdir)/appsettings.template.json" DestinationFiles="$(ProjectDir)/appsettings.json" />
  </Target>
  <Target Name="AppsettingsDevBuild">
    <Message Text="Generating appsettings.Development.json because it doesnt exist" Importance="High" />
    <Copy SourceFiles="$(ProjectDir)appsettings.Development.template.json" DestinationFiles="$(ProjectDir)appsettings.Development.json" />
  </Target>


  <!-- clean Belle when cleaning and rebuilding, but only in Visual Studio -->
  <Target Name="CleanPreconditions" AfterTargets="Clean" Condition="'$(SbnBuild)' == ''">
    <Message Text="-CleanPreconditions-" Importance="high" />
    <Message Text="Nothing to clean, as $(BellePath) does not exist." Importance="High" Condition="!Exists('$(BellePath)')" />
    <Message Text="Not cleaning (found src/preserve.belle)." Importance="High" Condition="Exists('$(BellePath)') and Exists('$(SolutionDir)preserve.belle')" />
    <Message Text="Remove $(BellePath)." Importance="High" Condition="Exists('$(BellePath)') and !Exists('$(SolutionDir)preserve.belle')" />
    <ItemGroup>
      <BelleLib Include="$(BellePath)" />
    </ItemGroup>
    <RemoveDir Directories="@(BelleLib)" Condition="Exists('$(BellePath)') and !Exists('$(SolutionDir)preserve.belle')" />

    <Message Text="Remove $(JsonSchemaPath)." Importance="High" Condition="Exists('$(JsonSchemaPath)') and !Exists('$(SolutionDir)preserve.jsonschema')" />
    <Delete Files="$(JsonSchemaPath)" Condition="Exists('$(JsonSchemaPath)') and !Exists('$(SolutionDir)preserve.jsonschema')" />
  </Target>
  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>
</Project>
