<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <RootNamespace>Sbn.Cms.Persistence.SqlCe</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\Sbn.Persistence.SqlCe.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sbn.Infrastructure\Sbn.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="System.Data.SqlServerCe">
        <HintPath>..\..\..\..\..\Program Files (x86)\Microsoft SQL Server Compact Edition\v4.0\Desktop\System.Data.SqlServerCe.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
