//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Sbn.ModelsBuilder.Embedded v9.1.0+aba021f90748cc785ddef384796ecfcb829d9634
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Sbn.Cms.Core.Models.PublishedContent;
using Sbn.Cms.Core.PublishedCache;
using Sbn.Cms.Infrastructure.ModelsBuilder;
using Sbn.Cms.Core;
using Sbn.Extensions;

namespace Sbn.Cms.Web.Common.PublishedModels
{
	/// <summary>recurso</summary>
	[PublishedModel("recurso")]
	public partial class Recurso : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		public new const string ModelTypeAlias = "recurso";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Recurso, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Recurso(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// detalle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("detalle")]
		public virtual global::Sbn.Cms.Core.Strings.IHtmlEncodedString Detalle => this.Value<global::Sbn.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "detalle");

		///<summary>
		/// documento
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("documento")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Sbn.Cms.Core.Models.Link> Documento => this.Value<global::System.Collections.Generic.IEnumerable<global::Sbn.Cms.Core.Models.Link>>(_publishedValueFallback, "documento");

		///<summary>
		/// entidad
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("entidad")]
		public virtual string Entidad => this.Value<string>(_publishedValueFallback, "entidad");

		///<summary>
		/// nombre
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nombre")]
		public virtual string Nombre => this.Value<string>(_publishedValueFallback, "nombre");

		///<summary>
		/// year
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("year")]
		public virtual string Year => this.Value<string>(_publishedValueFallback, "year");
	}
}
