//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Sbn.ModelsBuilder.Embedded v9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Sbn.Cms.Core.Models.PublishedContent;
using Sbn.Cms.Core.PublishedCache;
using Sbn.Cms.Infrastructure.ModelsBuilder;
using Sbn.Cms.Core;
using Sbn.Extensions;

namespace Sbn.Cms.Web.Common.PublishedModels
{
	/// <summary>Soportes-Bibliográficos</summary>
	[PublishedModel("recursos1")]
	public partial class Recursos1 : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		public new const string ModelTypeAlias = "recursos1";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Recursos1, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Recursos1(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// descripcion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("descripcion")]
		public virtual string Descripcion => this.Value<string>(_publishedValueFallback, "descripcion");

		///<summary>
		/// Palabras claves
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("palabrasClaves")]
		public virtual global::System.Collections.Generic.IEnumerable<string> PalabrasClaves => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "palabrasClaves");

		///<summary>
		/// Recursos a Mostrar
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		[ImplementPropertyType("recursosAMostrar")]
		public virtual decimal RecursosAmostrar => this.Value<decimal>(_publishedValueFallback, "recursosAMostrar");

		///<summary>
		/// Titulo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+80d72b2eb0e3b88e18b27100726da1525e75ede7")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("titulo")]
		public virtual string Titulo => this.Value<string>(_publishedValueFallback, "titulo");
	}
}
