//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Sbn.ModelsBuilder.Embedded v9.1.0+aba021f90748cc785ddef384796ecfcb829d9634
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Sbn.Cms.Core.Models.PublishedContent;
using Sbn.Cms.Core.PublishedCache;
using Sbn.Cms.Infrastructure.ModelsBuilder;
using Sbn.Cms.Core;
using Sbn.Extensions;

namespace Sbn.Cms.Web.Common.PublishedModels
{
	/// <summary>Vector Graphics (SVG)</summary>
	[PublishedModel("sbnMediaVectorGraphics")]
	public partial class SbnMediaVectorGraphics : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		public new const string ModelTypeAlias = "sbnMediaVectorGraphics";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SbnMediaVectorGraphics, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SbnMediaVectorGraphics(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Size: in bytes
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[ImplementPropertyType("sbnBytes")]
		public virtual long SbnBytes => this.Value<long>(_publishedValueFallback, "sbnBytes");

		///<summary>
		/// Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sbnExtension")]
		public virtual string SbnExtension => this.Value<string>(_publishedValueFallback, "sbnExtension");

		///<summary>
		/// Vector Graphics
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sbn.ModelsBuilder.Embedded", "9.1.0+aba021f90748cc785ddef384796ecfcb829d9634")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sbnFile")]
		public virtual string SbnFile => this.Value<string>(_publishedValueFallback, "sbnFile");
	}
}
